@startuml
left to right direction
actor DefaultUser as U
actor Admin as A

rectangle Website {
    usecase "Login" as UC1
    usecase "Register" as UC2
    usecase "View Home Page" as UC3
    usecase "View About Page" as UC4
    usecase "View Contact Page" as UC5
    usecase "View Blog Page" as UC6
    usecase "View Single Blog Page" as UC7
    usecase "Share Blog" as UC8
    usecase "Change Theme" as UC9
    UC1 --> UC3 : <<include>>
	UC2 --> UC1 : <<include>>
    UC3 --> UC9 : <<include>>
    UC4 --> UC9 : <<include>>
    UC5 --> UC9 : <<include>>
    UC6 --> UC9 : <<include>>
    UC7 --> UC9 : <<include>>
    UC7 --> UC8
    UC6 --> UC7 : <<include>>
}

rectangle AdminDashboard {
    usecase "View Admin Dashboard" as UC10
    usecase "View All Blogs" as UC11
    usecase "View All Users" as UC12
    usecase "Add Blog" as UC13
    usecase "Add User" as UC14
    UC10 --> UC11 : <<include>>
    UC10 --> UC12 : <<include>>
    UC10 --> UC13 : <<include>>
    UC10 --> UC14 : <<include>>
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6
U --> UC7
U --> UC8
U --> UC9

A --> UC10
A --> UC11
A --> UC12
A --> UC13
A --> UC14

@enduml
