@startuml
left to right direction
actor DefaultUser as U
actor Admin as A

rectangle Website {
    usecase "Login" as UC1
    usecase "Register" as UC2
    usecase "View Home Page" as UC3
    usecase "Send mesage to company" as UC5
    usecase "View Blog Page" as UC6
    usecase "View Single Blog Page" as UC7
    usecase "Share Blog" as UC8
    usecase "Change Theme" as UC9
    usecase "Book a meeting with company" as UC15
    UC1 --> UC3 : <<include>>
	  UC2 --> UC1 : <<include>>
    UC7 --> UC8
    UC6 --> UC7 : <<include>>
}

rectangle AdminDashboard {
    usecase "View All Blogs and Users" as UC11
    usecase "Add Blog" as UC13
    usecase "Add User" as UC14
    usecase "Delete Blog" as UC16
    usecase "Delete User" as UC17
}

U --> UC1
U --> UC2
U --> UC3
U --> UC5
U --> UC6
U --> UC7
U --> UC9
U --> UC15

A --> UC11
A --> UC13
A --> UC14
A --> UC16
A --> UC17

@enduml
